name = "hex-mv-poly-mathlib"
defaultTargets = ["HexMvPolyMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexMvPoly"
git = "https://github.com/leanprover/hex-mv-poly.git"
rev = "e25a580e1c8ee59d66408031bcb74ed5aca05b95"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "bc2b5505b543d9f0e6ef641901dab6c1bd97bf21"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "HexMvPolyMathlib"
