name = "hex-mv-poly-mathlib"
defaultTargets = ["HexMvPolyMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexMvPoly"
git = "https://github.com/leanprover/hex-mv-poly.git"
rev = "51f56155b0165ab8bd334cebce788a56c9e79b7a"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "d4bbb82b87704d3016c6c1d822ae1f77c793958a"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "da8a864cd17ccca780d8c76af403e88585bc4734"

[[lean_lib]]
name = "HexMvPolyMathlib"
